# Generated by Django 4.0.5 on 2022-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_participant_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=600)),
                ('Tests', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Input', models.CharField(max_length=200)),
                ('Expected_output', models.CharField(max_length=200)),
                ('Output_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='Password',
        ),
    ]
