# Generated by Django 4.0.5 on 2022-06-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_test_output_type_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(default='La somme de deux nombres', max_length=200),
        ),
    ]
