# Generated by Django 4.0.5 on 2022-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(default='timezone.now', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, upload_to='problem_image'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.ImageField(blank=True, upload_to='problem_statement'),
        ),
    ]
