# Generated by Django 4.0.5 on 2022-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_problem_description_problem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='processing_path',
            field=models.CharField(default='game_1.pde', max_length=200),
            preserve_default=False,
        ),
    ]
