# Generated by Django 4.0.5 on 2022-08-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_problem_processing_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrote_code', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('results', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, upload_to='Game_image')),
                ('Statement', models.ImageField(blank=True, upload_to='Game_statement')),
                ('Processing_Path', models.CharField(max_length=200)),
                ('Tests', models.CharField(max_length=200)),
                ('Score', models.IntegerField()),
                ('Default_Python_Code', models.TextField()),
                ('Number_Of_Tests', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='score',
            new_name='Score',
        ),
        migrations.AddField(
            model_name='participant',
            name='School',
            field=models.CharField(default='EMINES', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancement',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.participant'),
        ),
        migrations.AddField(
            model_name='advancement',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.game'),
        ),
    ]
