# Generated by Django 4.0.5 on 2022-08-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_advancement_game_delete_problem_delete_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancement',
            old_name='problem',
            new_name='Game',
        ),
        migrations.RenameField(
            model_name='advancement',
            old_name='player',
            new_name='Participant',
        ),
        migrations.RenameField(
            model_name='advancement',
            old_name='percentage',
            new_name='Percentage',
        ),
        migrations.RenameField(
            model_name='advancement',
            old_name='results',
            new_name='Results',
        ),
        migrations.RenameField(
            model_name='advancement',
            old_name='score',
            new_name='Score',
        ),
        migrations.RenameField(
            model_name='advancement',
            old_name='wrote_code',
            new_name='Wrote_Code',
        ),
        migrations.AddField(
            model_name='advancement',
            name='Number_Of_Tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='Number_Of_Tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='Solved_Problems',
            field=models.IntegerField(default=0),
        ),
    ]
