# Generated by Django 4.0.5 on 2022-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_problem_advancement_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancement',
            name='Game',
        ),
        migrations.RemoveField(
            model_name='advancement',
            name='Participant',
        ),
        migrations.AddField(
            model_name='advancement',
            name='Game_Id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancement',
            name='Participant_Id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
