# Generated by Django 4.0.5 on 2022-08-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_game_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancement',
            name='Game_Id',
        ),
        migrations.RemoveField(
            model_name='advancement',
            name='Participant_Id',
        ),
        migrations.AddField(
            model_name='advancement',
            name='Game',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancement',
            name='Participant',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.participant'),
            preserve_default=False,
        ),
    ]
