# Generated by Django 4.0.5 on 2022-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_advancement_used_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancement',
            name='Game',
        ),
        migrations.AddField(
            model_name='advancement',
            name='Game',
            field=models.ManyToManyField(to='app.game'),
        ),
        migrations.RemoveField(
            model_name='advancement',
            name='Participant',
        ),
        migrations.AddField(
            model_name='advancement',
            name='Participant',
            field=models.ManyToManyField(to='app.participant'),
        ),
    ]
