# Generated by Django 4.0.5 on 2022-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_advancement_game_advancement_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancement',
            name='Game',
        ),
        migrations.AddField(
            model_name='advancement',
            name='Game',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='advancement',
            name='Participant',
        ),
        migrations.AddField(
            model_name='advancement',
            name='Participant',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
