# Generated by Django 4.0.5 on 2022-08-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_advancement_game_advancement_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancement',
            old_name='Game',
            new_name='Game_Id',
        ),
        migrations.RenameField(
            model_name='advancement',
            old_name='Participant',
            new_name='Participant_Id',
        ),
    ]
