# Generated by Django 4.0.5 on 2022-08-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_number_test_game_id_remove_test_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancement',
            name='color',
            field=models.CharField(default='black', max_length=30),
        ),
    ]
