# Generated by Django 4.0.5 on 2022-08-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_advancement_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancement',
            old_name='color',
            new_name='Color',
        ),
    ]
